2

diff --git a/.github/workflows/list-from-meta.yml b/.github/workflows/list-from-meta.yml
--- a/.github/workflows/list-from-meta.yml
+++ b/.github/workflows/list-from-meta.yml
@@ -13,25 +13,34 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+    - name: Checkout code
+      uses: actions/checkout@v3
+
     - name: Clone specific branch and folder
       run: |
         git clone --depth 1 --branch meta https://github.com/MetaCubeX/meta-rules-dat.git
         cd meta-rules-dat
+        git sparse-checkout init --cone
+        git sparse-checkout set meta/geo/geosite
+
+    - name: List directory for debugging
+      run: |
+        cd meta-rules-dat/meta/geo/geosite
+        ls -R || echo "Directory not found"
 
     - name: Filter and clean .list files
       run: |
-        cd meta-rules-dat/geo
-        mkdir -p $GITHUB_WORKSPACE/processed-files
-        cd geosite
+        mkdir -p ./processed-files
+        cd meta-rules-dat/meta/geo/geosite
         for file in *.list; do
           if [ -f "$file" ]; then
-            sed 's/+//g' "$file" > ".$GITHUB_WORKSPACE/processed-files/$file"
+            sed 's/+//g' "$file" > "../../../processed-files/$file"
           fi
         done
 
     - name: Commit changes
       run: |
-        cd $GITHUB_WORKSPACE/processed-files
+        cd processed-files
         git init
         git config --global user.name "github-actions[bot]"
         git config --global user.email "github-actions[bot]@users.noreply.github.com"
